---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lstocks3/analisis.luisguacache.com/
    - /bin/cp -f index.html ${DEPLOYPATH}
    - /bin/cp -f favicon.png ${DEPLOYPATH}
    - /bin/cp -f README.md ${DEPLOYPATH}
    - /bin/cp -f robots.txt ${DEPLOYPATH}
    - /bin/cp -f sitemap.xml ${DEPLOYPATH}
    - /bin/cp -f 404.html ${DEPLOYPATH}
    - /bin/cp -Rf assets ${DEPLOYPATH}
    - /bin/cp -Rf downloads ${DEPLOYPATH}
    - /bin/cp -Rf docs ${DEPLOYPATH}
    - /bin/cp -Rf biblioteca ${DEPLOYPATH}
